language: php

php:
  - '7.1'
  - '7.2'
  - nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-text
